#Spring配置
spring:
    #数据库连接配置
  datasource:    url: jdbc:mysql://localhost:3306/java_redis?characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    
  #Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 6000 #连接超时时间(毫秒)
    lettuce:      pool:        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        
  devtools:
    restart:      enabled: true
      additional-paths: src/main/java

#mybatis 配置
mybatis:  configuration:    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:mapper/*.xml
  
  
#debug: true